CHANGE REPLICATION SOURCE TO
/* SOURCE_HOST='source_server_ip', */
SOURCE_HOST='192.168.56.101',
SOURCE_USER='replica_admin',
SOURCE_PASSWORD='adminPass',
SOURCE_LOG_FILE='mysql-bin.000001',
SOURCE_LOG_POS=4;
START REPLICA;
